# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide@0.14.1 
      with:
        path: 'src'
        
    - name: Test with pytest
      run: |
        pytest
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: "Create .netrc for Heroku Auth"
        shell: bash
        run: |
          `cat > ~/.netrc <<EOF
          machine api.heroku.com
              login $EMAIL
              password $HEROKU_AUTH_TOKEN
          machine git.heroku.com
              login $EMAIL
              password $HEROKU_AUTH_TOKEN
          EOF`
        env:
          EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
      - name: "Add remote"
        shell: "bash"
        run: |
          heroku git:remote --app ${{ secrets.HEROKU_APP_NAME }}
      - name: "Push to heroku"
        shell: "bash"
        run: |
          git push heroku HEAD:main 

      
